vim.filetype.add {
  extension = {
    sls = "sls.yaml.jinja",
    j2 = "jinja",
    tf = "terraform",
  },
  pattern = {
    [".*.service"] = "systemd",
    [".*.ya?ml.j2"] = "yaml.jinja",
    [".*/ansible/.*%.ya?ml"] = "yaml.ansible",
    [".*/defaults/.*%.ya?ml"] = "yaml.ansible",
    [".*/host_vars/.*%.ya?ml"] = "yaml.ansible",
    [".*/group_vars/.*%.ya?ml"] = "yaml.ansible",
    [".*/group_vars/.*/.*%.ya?ml"] = "yaml.ansible",
    [".*/playbook.*%.ya?ml"] = "yaml.ansible",
    [".*/playbooks/.*%.ya?ml"] = "yaml.ansible",
    [".*/roles/.*/tasks/.*%.ya?ml"] = "yaml.ansible",
    [".*/roles/.*/handlers/.*%.ya?ml"] = "yaml.ansible",
    [".*/tasks/.*%.ya?ml"] = "yaml.ansible",
    [".*/molecule/.*%.ya?ml"] = "yaml.ansible",
    [".*/templates/.*.yaml"] = "helm",
    [".*/templates/.*.tpl"] = "helm",
    [".*.conf.j2"] = "conf.jinja",
    [".*.yaml.j2"] = "yaml.jinja",
  },
}
