return { -- Highlight, edit, and navigate code
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  build = ':TSUpdate',
  config = function()
    local filetypes = {
      'astro',
      'bash',
      'c',
      'css',
      'go',
      'diff',
      'helm',
      'html',
      'ini',
      'jinja',
      'jinja_inline',
      'java',
      'javascript',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'ninja',
      'properties',
      'python',
      'query',
      'rst',
      'vim',
      'vimdoc',
      'terraform',
      'typescript',
      'toml',
      'yaml',
    }
    require('nvim-treesitter').install(filetypes)
  end,
}
