return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  dependencies = {
    {
      "mason-org/mason.nvim",
      opts = {},
    },
  },
  opts = {
    ensure_installed = {
      "ansible-language-server",
      "astro-language-server",
      "bash-language-server",
      "clangd",
      "css-lsp",
      "dockerfile-language-server",
      "emmet-language-server",
      "gh-actions-language-server",
      "gofumpt",
      "goimports",
      "golines",
      "gomodifytags",
      "gotests",
      "gopls",
      "htmx-lsp",
      "htmx-lsp",
      "impl",
      "lua-language-server",
      "pyright",
      "ruff",
      "shfmt",
      "sqlls",
      "stylua",
      "tailwindcss-language-server",
      "terraform-ls",
      "templ",
      "tflint",
      "prettier",
      "yaml-language-server",
    },
    run_on_start = false,
  },
}
